# Generated by Django 4.1.5 on 2023-02-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='correctionsreception',
            name='title',
        ),
        migrations.RemoveField(
            model_name='correctionssending',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
    ]
