# Generated by Django 4.1.7 on 2023-11-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_reportletter_options'),
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='home',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='Home.home'),
        ),
    ]
