# Generated by Django 4.1.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_publication_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='numero_folio',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de oficio actual'),
        ),
    ]
