# Generated by Django 4.1.3 on 2023-01-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
