# Generated by Django 4.1.3 on 2023-01-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Publication',
        ),
    ]
