# Generated by Django 4.1.3 on 2023-01-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_event_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.CreateModel(
            name='ProposalReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('start_date', models.DateTimeField(help_text='Fecha de Inicio', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha de Finalizacion', verbose_name='Fecha de Finalizacion')),
                ('notes', models.TextField(help_text='Notas', verbose_name='Notas')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_reception', to='events.publication')),
            ],
            options={
                'verbose_name': 'Recepción de propuestas',
                'verbose_name_plural': 'Recepción de propuestas',
            },
        ),
        migrations.CreateModel(
            name='FinalReportSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Dia', verbose_name='Dia')),
                ('start_time', models.TimeField(help_text='Hora de Inicio', verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(help_text='Hora de Finalizacion', verbose_name='Hora de Finalizacion')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report_sending', to='events.publication')),
            ],
            options={
                'verbose_name': 'Entrega  de dictamen final',
                'verbose_name_plural': 'Entrega  de dictamen final',
            },
        ),
        migrations.CreateModel(
            name='CorrectionsSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('start_date', models.DateTimeField(help_text='Fecha de Inicio', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha de Finalizacion', verbose_name='Fecha de Finalizacion')),
                ('notes', models.TextField(help_text='Notas', verbose_name='Notas')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_sending', to='events.publication')),
            ],
            options={
                'verbose_name': 'Envio de correcciones',
                'verbose_name_plural': 'Envio de correcciones',
            },
        ),
        migrations.CreateModel(
            name='CorrectionsReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('start_date', models.DateTimeField(help_text='Fecha de Inicio', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha de Finalizacion', verbose_name='Fecha de Finalizacion')),
                ('notes', models.TextField(help_text='Notas', verbose_name='Notas')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_reception', to='events.publication')),
            ],
            options={
                'verbose_name': 'Recepción de correccion de articulos',
                'verbose_name_plural': 'Recepción de correccion de articulos',
            },
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('start_date', models.DateTimeField(help_text='Fecha de Inicio', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha de Finalizacion', verbose_name='Fecha de Finalizacion')),
                ('notes', models.TextField(help_text='Notas', verbose_name='Notas')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_review', to='events.publication')),
            ],
            options={
                'verbose_name': 'Revisión de articulos',
                'verbose_name_plural': 'Revisión de articulos',
            },
        ),
        migrations.CreateModel(
            name='ArticlePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Dia', verbose_name='Dia')),
                ('start_time', models.TimeField(help_text='Hora de Inicio', verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(help_text='Hora de Finalizacion', verbose_name='Hora de Finalizacion')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_publication', to='events.publication')),
            ],
            options={
                'verbose_name': 'Publicación de articulos',
                'verbose_name_plural': 'Publicación de articulos',
            },
        ),
    ]
