# Generated by Django 4.1.3 on 2023-01-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_publication_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='home',
        ),
    ]
