# Generated by Django 4.1.3 on 2023-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_publication_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='numero_publicacion',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de publicación', null=True, unique=True, verbose_name='Numero de publicación'),
        ),
    ]
