# Generated by Django 4.1.3 on 2023-01-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_home_publication'),
        ('events', '0009_publication_numero_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='home',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.home'),
        ),
    ]
