# Generated by Django 4.1.3 on 2023-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_publication_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='current',
            field=models.BooleanField(default=False, help_text='Publicación actual', verbose_name='Publicación actual'),
        ),
    ]
