# Generated by Django 4.1.3 on 2023-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_publication_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='correctionsreception',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='correctionssending',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='proposalreception',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
    ]
