# Generated by Django 4.1.3 on 2023-01-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_home_convocatoria'),
        ('events', '0013_remove_publication_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='home',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.home'),
        ),
    ]
