# Generated by Django 4.1.3 on 2023-01-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_reviewerassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalReception',
        ),
    ]
