# Generated by Django 4.1.3 on 2023-01-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_home_convocatoria'),
        ('events', '0016_delete_proposalreception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='home',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.home'),
        ),
    ]
