# Generated by Django 4.1.5 on 2023-02-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_articlereview_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewerAssignment',
        ),
    ]
