# Generated by Django 4.1.3 on 2023-01-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['title'], 'verbose_name': 'Página principal', 'verbose_name_plural': 'Página principal'},
        ),
        migrations.AddField(
            model_name='home',
            name='brand_image',
            field=models.ImageField(default='static/img/logo.png', upload_to='home', verbose_name='Imagen de marca'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='static/img/itssmt.png', upload_to='home', verbose_name='Imagen'),
        ),
    ]
