# Generated by Django 4.1.7 on 2023-09-22 12:32

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('template_accepted', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_template_accepted, verbose_name='Plantilla de aceptación')),
                ('template_rejected', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_template_rejected, verbose_name='Plantilla de rechazo')),
                ('president', models.CharField(max_length=100, verbose_name='Presidente del comité de arbitraje')),
                ('home', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_letters', to='Home.home', verbose_name='Página principal')),
            ],
            options={
                'verbose_name': 'Carta de reporte',
                'verbose_name_plural': 'Cartas de reporte',
            },
        ),
    ]
