# Generated by Django 4.1.3 on 2023-01-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_home_options_home_brand_image_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='brand_image',
            field=models.ImageField(default='home/logo.png', upload_to='home', verbose_name='Imagen de marca'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='home/itssmt.png', upload_to='home', verbose_name='Imagen'),
        ),
    ]
