# Generated by Django 4.1.7 on 2023-10-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_reportletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportletter',
            options={'verbose_name': 'Carta de dictamen', 'verbose_name_plural': 'Cartas de dictamenes'},
        ),
    ]
