# Generated by Django 4.1.7 on 2023-11-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_reportletter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='acept_template',
        ),
        migrations.RemoveField(
            model_name='home',
            name='reject_template',
        ),
    ]
