# Generated by Django 4.1.3 on 2023-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_home_brand_image_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='home/itssmt.png', upload_to='home', verbose_name='Imagen Principal'),
        ),
    ]
