# Generated by Django 4.1.3 on 2023-01-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='brand_image',
            field=models.ImageField(default='home/logo1.png', upload_to='home', verbose_name='Imagen de marca'),
        ),
    ]
