# Generated by Django 4.1.7 on 2023-11-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_home_acept_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionletter',
            name='current_number',
        ),
    ]
