# Generated by Django 4.1.3 on 2023-01-01 08:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_home_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='brand_image',
            field=models.ImageField(default='home/logo1.png', upload_to=core.models.custom_upload_to, verbose_name='Imagen de marca'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='home/itssmt.png', upload_to=core.models.custom_upload_to, verbose_name='Imagen Principal'),
        ),
    ]
