# Generated by Django 4.1.3 on 2023-01-02 06:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_home_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_to_brand, verbose_name='Imagen de marca'),
        ),
        migrations.AlterField(
            model_name='home',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_to_favicon, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_to_image, verbose_name='Imagen Principal'),
        ),
    ]
