# Generated by Django 4.1.3 on 2023-01-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_publication_home'),
        ('core', '0008_alter_home_brand_image_alter_home_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.publication', verbose_name='Publicación'),
        ),
    ]
