# Generated by Django 4.1.3 on 2023-01-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_home_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='publication',
        ),
    ]
