# Generated by Django 4.1.5 on 2023-01-20 00:22

import core.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_home_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to_article_template, verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Plantilla de artículo',
                'verbose_name_plural': 'Plantillas de artículos',
                'ordering': ['name'],
            },
        ),
    ]
