# Generated by Django 4.1.5 on 2023-01-21 21:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_articletemplate_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='acept_template',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to_acept_template, verbose_name='Plantilla de aceptación'),
        ),
        migrations.AddField(
            model_name='home',
            name='no_acept_template',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to_reject_template, verbose_name='Plantilla de no aceptación'),
        ),
    ]
