# Generated by Django 4.1.5 on 2023-01-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_home_acept_template_home_no_acept_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='no_acept_template',
            new_name='reject_template',
        ),
    ]
