# Generated by Django 4.1.5 on 2023-01-26 22:22

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_no_acept_template_home_reject_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to_article_template, verbose_name='Plantilla')),
                ('president', models.CharField(max_length=100, verbose_name='Presidente del comité de arbitraje')),
                ('president_firm', models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_firm_pre, verbose_name='Firma del presidente')),
                ('secretary', models.CharField(max_length=100, verbose_name='Secretario del comité de arbitraje')),
                ('secretary_firm', models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_firm_sec, verbose_name='Firma del secretario')),
                ('seal', models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_seal, verbose_name='Sello del departamento de investigación')),
                ('home', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reception_letters', to='core.home', verbose_name='Página principal')),
            ],
            options={
                'verbose_name': 'Carta de recepción',
                'verbose_name_plural': 'Cartas de recepción',
                'ordering': ['name'],
            },
        ),
    ]
