# Generated by Django 4.1.5 on 2023-01-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_receptionletter_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionletter',
            options={'verbose_name': 'Carta de recepción', 'verbose_name_plural': 'Cartas de recepción'},
        ),
        migrations.RemoveField(
            model_name='receptionletter',
            name='name',
        ),
    ]
