# Generated by Django 4.1.5 on 2023-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_receptionletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionletter',
            name='current_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de oficio actual'),
        ),
    ]
