# Generated by Django 4.1.5 on 2023-02-05 00:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_receptionletter_current_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionletter',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_template_reception_letter, verbose_name='Plantilla'),
        ),
    ]
