# Generated by Django 4.1.5 on 2023-02-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recepcion_Propuestas', '0001_initial'),
        ('Eventos', '0001_initial'),
        ('registration', '0002_alter_profile_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100, unique=True, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='RefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('start_date', models.DateTimeField(help_text='Fecha de Inicio', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha de Finalizacion', verbose_name='Fecha de Finalizacion')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignment', to='Eventos.publication')),
            ],
            options={
                'verbose_name': 'Asignación de revisores',
                'verbose_name_plural': 'Asignación de revisores',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Recepcion_Propuestas.articleproposal')),
                ('referee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Asignacion_Arbitros.refereeassignment')),
                ('referees', models.ManyToManyField(blank=True, related_name='assignments', to='registration.profile', verbose_name='arbitros')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='ArticleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Recepcion_Propuestas.articleproposal', verbose_name='Artículo')),
                ('profiles', models.ManyToManyField(related_name='articles', to='Asignacion_Arbitros.profile', verbose_name='Perfiles')),
                ('referee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Asignacion_Arbitros.refereeassignment', verbose_name='Asignación de arbitros')),
            ],
            options={
                'verbose_name': 'Perfil de artículo',
                'verbose_name_plural': 'Perfiles de artículo',
            },
        ),
    ]
