# Generated by Django 4.1.5 on 2023-02-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
        ('Recepcion_Propuestas', '0001_initial'),
        ('registration', '0001_initial'),
        ('Asignacion_Arbitros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Recepcion_Propuestas.articleproposal'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Eventos.publication', verbose_name='Publicación'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='referees',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='registration.profile', verbose_name='arbitros'),
        ),
        migrations.AddField(
            model_name='articleprofile',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Recepcion_Propuestas.articleproposal', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='articleprofile',
            name='profiles',
            field=models.ManyToManyField(related_name='articles', to='Asignacion_Arbitros.profile', verbose_name='Perfiles'),
        ),
        migrations.AddField(
            model_name='articleprofile',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_profiles', to='Eventos.publication', verbose_name='Publicación'),
        ),
    ]
