# Generated by Django 4.1.5 on 2023-02-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_delete_reviewerassignment'),
        ('reviewer_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewerAssignment',
            new_name='RefereeAssignment',
        ),
    ]
