# Generated by Django 4.1.5 on 2023-02-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(choices=[('P', 'Pendiente'), ('A', 'Asignado')], default=False, verbose_name='Estado'),
        ),
    ]
