# Generated by Django 4.1.5 on 2023-02-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0019_alter_articleproposal_new_school_and_more'),
        ('registration', '0010_remove_profile_first_join_remove_profile_school'),
        ('reviewer_assignment', '0002_rename_reviewerassignment_refereeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='proposal_reception.articleproposal')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='registration.profile')),
                ('referee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviewer_assignment.refereeassignment')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
