# Generated by Django 4.1.5 on 2023-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0003_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Asignado')], default='P', max_length=1, verbose_name='Estatus'),
        ),
    ]
