# Generated by Django 4.1.5 on 2023-02-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0019_alter_articleproposal_new_school_and_more'),
        ('reviewer_assignment', '0003_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Perfil de artículo',
                'verbose_name_plural': 'Perfiles de artículo',
            },
        ),
        migrations.CreateModel(
            name='ArticleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='proposal_reception.articleproposal')),
                ('profiles', models.ManyToManyField(related_name='articles', to='reviewer_assignment.profile')),
            ],
            options={
                'verbose_name': 'Perfil de artículo',
                'verbose_name_plural': 'Perfiles de artículo',
            },
        ),
    ]
