# Generated by Django 4.1.5 on 2023-02-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0002_alter_articleproposal_new_school'),
        ('Asignacion_Arbitros', '0004_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Recepcion_Propuestas.articleproposal', verbose_name='Artículo'),
        ),
    ]
