# Generated by Django 4.1.5 on 2023-02-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0019_alter_articleproposal_new_school_and_more'),
        ('registration', '0010_remove_profile_first_join_remove_profile_school'),
        ('reviewer_assignment', '0004_profile_articleprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='referee',
        ),
        migrations.AddField(
            model_name='assignment',
            name='referees',
            field=models.ManyToManyField(related_name='assignments', to='registration.profile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='proposal_reception.articleproposal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(max_length=100, unique=True, verbose_name='Perfil'),
        ),
    ]
