# Generated by Django 4.1.5 on 2023-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0005_alter_assignment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprofile',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='articles', to='Asignacion_Arbitros.profile', verbose_name='Perfiles'),
        ),
    ]
