# Generated by Django 4.1.5 on 2023-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_profile_first_join_remove_profile_school'),
        ('reviewer_assignment', '0005_alter_profile_options_remove_assignment_referee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='referees',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignments', to='registration.profile'),
        ),
    ]
