# Generated by Django 4.1.7 on 2023-11-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0006_assignment_created_assignment_modified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleProfile',
        ),
    ]
