# Generated by Django 4.1.5 on 2023-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_assignment', '0006_alter_assignment_referees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
