# Generated by Django 4.1.5 on 2023-02-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
        ('Asignacion_Arbitros', '0006_alter_articleprofile_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprofile',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_profiles', to='Eventos.publication', verbose_name='Publicación'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Eventos.publication', verbose_name='Publicación'),
        ),
    ]
