# Generated by Django 4.1.5 on 2023-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0007_alter_articleprofile_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleprofile',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Perfiles asignados')], default='P', max_length=1, verbose_name='Estatus'),
        ),
    ]
