# Generated by Django 4.1.5 on 2023-02-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_profile_first_join_remove_profile_school'),
        ('reviewer_assignment', '0008_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleprofile',
            name='referee_assignment',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='reviewer_assignment.refereeassignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='referees',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='registration.profile', verbose_name='arbitros'),
        ),
    ]
