# Generated by Django 4.1.5 on 2023-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0008_articleprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
    ]
