# Generated by Django 4.1.5 on 2023-02-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0019_alter_articleproposal_new_school_and_more'),
        ('reviewer_assignment', '0009_articleprofile_referee_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprofile',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='proposal_reception.articleproposal', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='articleprofile',
            name='profiles',
            field=models.ManyToManyField(related_name='articles', to='reviewer_assignment.profile', verbose_name='Perfiles'),
        ),
        migrations.AlterField(
            model_name='articleprofile',
            name='referee_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='reviewer_assignment.refereeassignment', verbose_name='Asignación de arbitros'),
        ),
    ]
