# Generated by Django 4.1.5 on 2023-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_type_user'),
        ('Asignacion_Arbitros', '0009_assignment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='referees',
            field=models.ManyToManyField(related_name='assignments', to='registration.profile', verbose_name='arbitros'),
        ),
    ]
