# Generated by Django 4.1.3 on 2022-11-30 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_is_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Escuela'},
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Solo se permiten 10 números')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^((http|https):\\/\\/)?(www\\.)?([a-zA-Z0-9]+)\\.([a-zA-Z]{2,5})$', 'Formato de dirección web inválido')], verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='school',
            name='zip_code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Solo se permiten 5 números')], verbose_name='Código postal'),
        ),
    ]
