# Generated by Django 4.1.5 on 2023-03-03 10:18

import apps.correction_reception.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asignacion_Arbitros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correction_file', models.FileField(upload_to=apps.correction_reception.models.custom_upload__to_correction, verbose_name='Plantilla corregida')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='Asignacion_Arbitros.assignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Corrección',
                'verbose_name_plural': 'Correcciones',
            },
        ),
    ]
