# Generated by Django 4.1.5 on 2023-03-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0001_initial'),
        ('Recepcion_Correcciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecorrection',
            name='assignment',
        ),
        migrations.AddField(
            model_name='articlecorrection',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='Recepcion_Propuestas.articleproposal', verbose_name='Artículo'),
        ),
    ]
