# Generated by Django 4.1.5 on 2023-03-03 23:20

import apps.correction_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Correcciones', '0002_remove_articlecorrection_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecorrection',
            name='correction_file',
            field=models.FileField(null=True, upload_to=apps.correction_reception.models.custom_upload__to_correction, verbose_name='Plantilla corregida'),
        ),
    ]
