# Generated by Django 4.1.7 on 2023-03-17 03:13

import apps.correction_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Correcciones', '0004_articlecorrection_correction_file_as_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecorrection',
            name='correction_file',
            field=models.FileField(max_length=255, null=True, upload_to=apps.correction_reception.models.custom_upload__to_correction, verbose_name='Plantilla corregida'),
        ),
        migrations.AlterField(
            model_name='articlecorrection',
            name='correction_file_as_pdf',
            field=models.FileField(max_length=255, null=True, upload_to=apps.correction_reception.models.custom_upload__to_correction, verbose_name='Plantilla corregida en PDF'),
        ),
    ]
