# Generated by Django 4.1.7 on 2023-12-01 23:59

import apps.correction_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Correcciones', '0005_alter_articlecorrection_correction_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecorrection',
            name='numbering_line_file',
            field=models.FileField(max_length=255, null=True, upload_to=apps.correction_reception.models.custom_upload__to_numbering_line, verbose_name='Plantilla con numeración de líneas'),
        ),
        migrations.AlterField(
            model_name='articlecorrection',
            name='correction_file_as_pdf',
            field=models.FileField(max_length=255, null=True, upload_to=apps.correction_reception.models.custom_upload__to_correction_as_pdf, verbose_name='Plantilla corregida en PDF'),
        ),
    ]
