# Generated by Django 4.1.7 on 2023-12-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Correcciones', '0006_articlecorrection_numbering_line_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecorrection',
            name='numbering_line_file',
        ),
    ]
