# Generated by Django 4.1.5 on 2023-02-21 19:11

import apps.proposal_reception.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
        ('registration', '0001_initial'),
        ('Escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('modality', models.CharField(choices=[('1', 'Investigación aplicada'), ('2', 'Investigación básica'), ('3', 'Divulgación'), ('4', 'Revisión (review)'), ('5', 'Ensayo'), ('6', 'Nota Científica')], db_index=True, max_length=1, verbose_name='Modalidad')),
                ('new_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institución NO normalizada')),
                ('template', models.FileField(upload_to=apps.proposal_reception.models.custom_upload_to_user_template, verbose_name='Plantilla')),
                ('status', models.CharField(choices=[('1', 'En espera'), ('2', 'Recibido')], db_index=True, default='1', max_length=1, verbose_name='Estatus')),
                ('reception_letter', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_reception_letter, verbose_name='Carta de recepción')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_proposal', to='registration.profile', verbose_name='Autor')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_proposals', to='Eventos.publication', verbose_name='Publicación')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_proposals', to='Escuelas.school', verbose_name='Institución de adscripción')),
            ],
            options={
                'verbose_name': 'Propuesta de artículo',
                'verbose_name_plural': 'Propuestas de artículos',
            },
        ),
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(help_text='Máximo 2 nombres', max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('article_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='Recepcion_Propuestas.articleproposal', verbose_name='Propuesta de artículo')),
            ],
            options={
                'verbose_name': 'Coautor',
                'verbose_name_plural': 'Coautores',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=apps.proposal_reception.models.custom_upload_to_user_images, verbose_name='Imagen')),
                ('article_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_images', to='Recepcion_Propuestas.articleproposal', verbose_name='Propuesta de artículo')),
            ],
            options={
                'verbose_name': 'Imagen del artículo',
                'verbose_name_plural': 'Imagenes del artículo',
            },
        ),
    ]
