# Generated by Django 4.1.5 on 2023-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproposal',
            name='new_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Crédito de escuela'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='status',
            field=models.CharField(choices=[('1', 'En espera'), ('2', 'Recibido'), ('3', 'En revisión'), ('4', 'Sin corrergir'), ('5', 'Corregido'), ('6', 'Aceptado'), ('7', 'Rechazado')], db_index=True, default='1', max_length=1, verbose_name='Estatus'),
        ),
    ]
