# Generated by Django 4.1.3 on 2023-01-17 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_delete_proposalreception'),
        ('proposal_reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreception',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_reception', to='events.publication', verbose_name='Publicación'),
        ),
        migrations.CreateModel(
            name='ArticleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='Nuevo envento', help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('author', models.CharField(default='Nuevo envento', help_text='Autor', max_length=100, verbose_name='Autor')),
                ('email', models.EmailField(default='Nuevo envento', help_text='Correo', max_length=100, verbose_name='Correo')),
                ('abstract', models.TextField(default='Nuevo envento', help_text='Resumen', max_length=100, verbose_name='Resumen')),
                ('keywords', models.TextField(default='Nuevo envento', help_text='Palabras clave', max_length=100, verbose_name='Palabras clave')),
                ('file', models.FileField(default='Nuevo envento', help_text='Archivo', upload_to='article_proposals', verbose_name='Archivo')),
                ('proposal_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_proposals', to='proposal_reception.proposalreception', verbose_name='Recepción de propuestas')),
            ],
            options={
                'verbose_name': 'Propuesta de artículo',
                'verbose_name_plural': 'Propuestas de artículos',
            },
        ),
    ]
