# Generated by Django 4.1.5 on 2023-02-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproposal',
            name='new_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Credito de escuela'),
        ),
    ]
