# Generated by Django 4.1.5 on 2023-02-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
        ('Recepcion_Propuestas', '0002_alter_articleproposal_new_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproposal',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_proposals', to='Eventos.publication', verbose_name='Publicación'),
        ),
    ]
