# Generated by Django 4.1.3 on 2023-01-18 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_profile_user'),
        ('school', '0004_alter_school_address_alter_school_country_and_more'),
        ('proposal_reception', '0002_alter_proposalreception_publication_articleproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleproposal',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='articleproposal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='articleproposal',
            name='file',
        ),
        migrations.RemoveField(
            model_name='articleproposal',
            name='keywords',
        ),
        migrations.AddField(
            model_name='articleproposal',
            name='modality',
            field=models.CharField(choices=[('1', 'Investigación aplicada'), ('2', 'Investigación básica'), ('3', 'Divulgación'), ('4', 'Revisión (review)'), ('5', 'Ensayo'), ('6', 'Nota Científica')], default=0, help_text='Seleccione la modalidad de su artículo', max_length=1, verbose_name='Modalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleproposal',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='article_proposals', to='school.school', verbose_name='Institución de adscripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleproposal',
            name='template',
            field=models.FileField(default=0, upload_to='templates/{author.user.username}/', verbose_name='Plantilla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_proposal', to='registration.profile', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='title',
            field=models.CharField(help_text='Debe ser un titulo no muy largo', max_length=100, verbose_name='Titulo'),
        ),
        migrations.CreateModel(
            name='ProposalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='images/{article_proposal.author.user.username}/', verbose_name='Imagen')),
                ('article_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_images', to='proposal_reception.articleproposal', verbose_name='Propuesta de artículo')),
            ],
            options={
                'verbose_name': 'Imagen de la propuesta',
                'verbose_name_plural': 'Imagenes de la propuesta',
            },
        ),
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(help_text='Máximo 2 nombres', max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('article_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='proposal_reception.articleproposal', verbose_name='Propuesta de artículo')),
            ],
            options={
                'verbose_name': 'Coautor',
                'verbose_name_plural': 'Coautores',
            },
        ),
    ]
