# Generated by Django 4.1.3 on 2023-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0004_rename_proposalimage_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Imagen del artículo', 'verbose_name_plural': 'Imagenes del artículo'},
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='modality',
            field=models.CharField(choices=[('1', 'Investigación aplicada'), ('2', 'Investigación básica'), ('3', 'Divulgación'), ('4', 'Revisión (review)'), ('5', 'Ensayo'), ('6', 'Nota Científica')], db_index=True, help_text='Seleccione la modalidad de su artículo', max_length=1, verbose_name='Modalidad'),
        ),
    ]
