# Generated by Django 4.1.5 on 2023-01-20 00:22

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0005_alter_articleimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=apps.proposal_reception.models.custom_upload_to_user_images, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='template',
            field=models.FileField(upload_to=apps.proposal_reception.models.custom_upload_to_user_template, verbose_name='Plantilla'),
        ),
    ]
