# Generated by Django 4.1.7 on 2023-11-16 20:31

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0006_articleproposal_dictamen_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='rights_transfer_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_rights_transfer_letter, verbose_name='Carta de cesión de derechos'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='status',
            field=models.CharField(choices=[('1', 'En espera'), ('2', 'Recibido'), ('3', 'En revisión'), ('4', 'Sin corregir'), ('5', 'Corregido'), ('6', 'En dictamen'), ('7', 'Aceptado'), ('8', 'Rechazado'), ('9', 'Publicado')], db_index=True, default='1', max_length=2, verbose_name='Estatus'),
        ),
    ]
