# Generated by Django 4.1.5 on 2023-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0007_alter_coauthor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coauthor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
