# Generated by Django 4.1.7 on 2023-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0006_assignment_created_assignment_modified'),
        ('Recepcion_Propuestas', '0008_alter_articleproposal_rights_transfer_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='profiles',
            field=models.ManyToManyField(related_name='article_proposals', to='Asignacion_Arbitros.profile', verbose_name='Perfiles'),
        ),
    ]
