# Generated by Django 4.1.5 on 2023-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0008_alter_coauthor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='is_approved',
            field=models.BooleanField(null=True, verbose_name='Aprobado'),
        ),
    ]
