# Generated by Django 4.1.5 on 2023-01-21 19:34

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0009_articleproposal_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='dictamen',
            field=models.FileField(blank=True, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_user_dictamen, verbose_name='Dictamen'),
        ),
    ]
