# Generated by Django 4.1.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0010_alter_articleproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproposal',
            name='status',
            field=models.CharField(choices=[('1', 'En espera'), ('2', 'Recibido'), ('3', 'En revisión'), ('4', 'Sin corregir'), ('5', 'Corregido'), ('6', 'En recepción'), ('7', 'En dictamen'), ('8', 'Aceptado'), ('9', 'Rechazado'), ('10', 'Pendiente'), ('11', 'Publicado')], db_index=True, default='1', max_length=2, verbose_name='Estatus'),
        ),
    ]
