# Generated by Django 4.1.5 on 2023-01-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0010_articleproposal_dictamen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleproposal',
            name='dictamen',
        ),
        migrations.RemoveField(
            model_name='articleproposal',
            name='is_approved',
        ),
    ]
