# Generated by Django 4.1.5 on 2023-01-25 08:41

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0011_remove_articleproposal_dictamen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='reception_letter',
            field=models.FileField(blank=True, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_user_dictamen, verbose_name='Carta de recepción'),
        ),
        migrations.AddField(
            model_name='articleproposal',
            name='status',
            field=models.CharField(choices=[('1', 'En espera'), ('2', 'Recibido')], db_index=True, default='1', max_length=1, verbose_name='Estatus'),
        ),
    ]
