# Generated by Django 4.1.7 on 2023-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0011_alter_articleproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='DOI',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI'),
        ),
    ]
