# Generated by Django 4.1.7 on 2023-11-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0011_alter_articleproposal_status'),
        ('Recepcion_Propuestas', '0011_articleproposal_doi'),
    ]

    operations = [
    ]
