# Generated by Django 4.1.5 on 2023-01-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0012_articleproposal_reception_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalreception',
            name='notes',
        ),
    ]
