# Generated by Django 4.1.7 on 2023-12-02 03:18

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0012_articleproposal_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='numbering_line_file',
            field=models.FileField(max_length=255, null=True, upload_to=apps.proposal_reception.models.custom_upload__to_numbering_line, verbose_name='Plantilla con numeración de líneas'),
        ),
    ]
