# Generated by Django 4.1.7 on 2023-11-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0012_merge_20231127_1154'),
        ('Recepcion_Propuestas', '0012_merge_20231127_1527'),
    ]

    operations = [
    ]
