# Generated by Django 4.1.7 on 2023-12-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion_Propuestas', '0013_articleproposal_numbering_line_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleproposal',
            name='DOI',
        ),
    ]
