# Generated by Django 4.1.5 on 2023-02-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0013_remove_proposalreception_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titulo'),
        ),
    ]
