# Generated by Django 4.1.5 on 2023-02-05 00:45

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0014_articleproposal_slug_alter_articleproposal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproposal',
            name='new_school',
            field=models.CharField(default='nada', max_length=100, verbose_name='Institución de adscripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='modality',
            field=models.CharField(choices=[('1', 'Investigación aplicada'), ('2', 'Investigación básica'), ('3', 'Divulgación'), ('4', 'Revisión (review)'), ('5', 'Ensayo'), ('6', 'Nota Científica')], db_index=True, max_length=1, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='articleproposal',
            name='reception_letter',
            field=models.FileField(blank=True, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_reception_letter, verbose_name='Carta de recepción'),
        ),
    ]
