# Generated by Django 4.1.5 on 2023-02-05 02:01

import apps.proposal_reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_reception', '0015_articleproposal_new_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproposal',
            name='reception_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.proposal_reception.models.custom_upload_to_reception_letter, verbose_name='Carta de recepción'),
        ),
    ]
