# Generated by Django 4.1.5 on 2023-03-01 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('Asignacion_Arbitros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Asignacion_Arbitros.assignment', verbose_name='Asignación')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='registration.profile', verbose_name='Arbitro')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField(verbose_name='Línea')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('value', models.BooleanField(default=False, verbose_name='Corregido')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Revision_Articulo.review', verbose_name='Revisión')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
