# Generated by Django 4.1.5 on 2023-02-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0010_alter_assignment_referees'),
        ('Revision_Articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Asignacion_Arbitros.assignment', verbose_name='Asignación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
