# Generated by Django 4.1.5 on 2023-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado'),
        ),
    ]
