# Generated by Django 4.1.5 on 2023-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0002_alter_review_assignment_alter_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='line',
            field=models.PositiveIntegerField(default=1, verbose_name='Línea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.BooleanField(verbose_name='Corregido'),
        ),
    ]
