# Generated by Django 4.1.5 on 2023-02-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0010_alter_assignment_referees'),
        ('Revision_Articulo', '0003_note_line_alter_note_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Asignacion_Arbitros.assignment', verbose_name='Asignación'),
        ),
    ]
