# Generated by Django 4.1.7 on 2023-03-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0003_alter_review_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dictamen',
            field=models.CharField(choices=[('1', 'Aceptado'), ('2', 'Rechazado')], default='1', max_length=1, verbose_name='Dictamen'),
        ),
    ]
