# Generated by Django 4.1.7 on 2023-03-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0005_alter_review_dictamen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Arbitraje', 'verbose_name_plural': 'Arbitrajes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Revision_Articulo.review', verbose_name='Arbitraje'),
        ),
    ]
