# Generated by Django 4.1.7 on 2023-10-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0006_alter_review_options_alter_note_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
    ]
