# Generated by Django 4.1.7 on 2023-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0007_alter_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.BooleanField(null=True, verbose_name='Corregido'),
        ),
    ]
