# Generated by Django 4.1.7 on 2023-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0008_alter_note_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.BooleanField(default=False, verbose_name='Corregido'),
        ),
    ]
