# Generated by Django 4.1.7 on 2023-11-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revision_Articulo', '0008_note_created_note_modified'),
        ('Revision_Articulo', '0009_alter_note_value'),
    ]

    operations = [
    ]
