# Generated by Django 4.1.5 on 2023-02-18 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Solo se permiten 5 números')], verbose_name='Código postal')),
                ('country', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Solo se permiten 10 números')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('website', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^((http|https):\\/\\/)?(www\\.)?([a-zA-Z0-9]+)\\.([a-zA-Z]{2,5})$', 'Formato de dirección web inválido')], verbose_name='Sitio web')),
                ('is_external', models.BooleanField(default=False, verbose_name='Externo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Escuela',
                'ordering': ['name'],
            },
        ),
    ]
