# Generated by Django 4.1.3 on 2022-11-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=100, verbose_name='Código postal')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('website', models.CharField(max_length=100, verbose_name='Sitio web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
