# Generated by Django 4.1.5 on 2023-03-01 08:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-ZñÑáéíóúÁÉÍÓÚ])*(\\s([a-zA-ZñÑáéíóúÁÉÍÓÚ])*)*$', 'Solo se permiten letras')], verbose_name='Nombre')),
                ('is_external', models.BooleanField(default=False, verbose_name='Externo')),
            ],
            options={
                'verbose_name': 'Escuela',
                'ordering': ['name'],
            },
        ),
    ]
