# Generated by Django 4.1.3 on 2022-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Externo'),
        ),
    ]
