# Generated by Django 4.1.5 on 2023-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion_Arbitros', '0005_alter_assignment_article'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='article_profiles',
            field=models.ManyToManyField(blank=True, related_name='article_profiles', to='Asignacion_Arbitros.profile', verbose_name='Perfiles de articulos'),
        ),
    ]
