# Generated by Django 4.1.5 on 2023-02-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_profile_created_at_remove_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='article_profiles',
            new_name='profiles',
        ),
    ]
