# Generated by Django 4.1.7 on 2023-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_article_profiles_profile_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(blank=True, choices=[('1', 'Autor'), ('2', 'Arbitro')], max_length=1, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
