# Generated by Django 4.1.3 on 2022-12-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_first_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_join',
            field=models.BooleanField(default=False),
        ),
    ]
