# Generated by Django 4.1.3 on 2023-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_profile_first_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('1', 'Autor'), ('2', 'Evaluador')], default='0', max_length=1, verbose_name='Tipo de usuario'),
        ),
    ]
