# Generated by Django 4.1.3 on 2023-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_profile_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('1', 'Autor'), ('2', 'Evaluador')], max_length=1, verbose_name='Tipo de usuario'),
        ),
    ]
