# Generated by Django 4.1.5 on 2023-02-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_join',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
